# -*- coding: utf-8 -*-
"""Códigos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqmvsrqWlVnGjVvaoDI1sLzaDcazpxkC

# **Primera propuesta**
"""

import subprocess
import sys

def ejecutar_comando(comando):
    """Ejecuta un comando en el sistema y maneja los errores."""
    try:
        subprocess.check_call(comando, shell=True)
    except subprocess.CalledProcessError as e:
        print(f"Error ejecutando el comando: {comando}")
        print(f"Detalles: {e}")
        sys.exit(1)

def instalar_docker():
    """Instala Docker en el sistema si no está instalado."""
    print("Comprobando si Docker está instalado...")
    try:
        subprocess.check_call("docker --version", shell=True)
        print("Docker ya está instalado.")
    except subprocess.CalledProcessError:
        print("Docker no encontrado. Instalando Docker...")
        # Instalar dependencias necesarias para Ubuntu
        comandos = [
            "sudo apt update",
            "sudo apt install -y apt-transport-https ca-certificates curl software-properties-common",
            "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -",
            "sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'",
            "sudo apt update",
            "sudo apt install -y docker-ce"
        ]
        for comando in comandos:
            ejecutar_comando(comando)
        print("Docker instalado correctamente.")

def ejecutar_imagen_docker(imagen):
    """Ejecuta la imagen Docker especificada."""
    if not imagen:
        print("No se proporcionó el nombre de la imagen. Abortando...")
        sys.exit(1)

    print(f"Ejecutando la imagen Docker: {imagen}")
    comando = f"sudo docker run -d --name mi_contenedor {imagen}"
    ejecutar_comando(comando)
    print(f"El contenedor con la imagen {imagen} se está ejecutando correctamente.")

if _name_ == "_main_":
    # Instalar Docker si no está instalado
    instalar_docker()

    # Solicitar el nombre de la imagen Docker
    imagen_docker = input("Introduce el nombre de la imagen Docker que deseas ejecutar (por ejemplo, 'nginx' o 'mi-imagen:latest'): ")

    # Ejecutar la imagen Docker proporcionada
    ejecutar_imagen_docker(imagen_docker)

"""# **Segunda propuesta**

Esta propuesta ya incluye la creación y manejo de un docker-compose.yml, y de aspectos básicos del cluster
"""

import subprocess
import sys
import os
import platform
import shutil



# Función para verificar si Docker está instalado

def is_docker_installed():

    """Verifica si Docker está instalado en el sistema."""
    try:
        # Ejecuta 'docker --version' para verificar si Docker está instalado
        subprocess.run(["docker", "--version"], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print("Docker está instalado.")
        return True

    except subprocess.CalledProcessError:
        print("Docker no está instalado.")
        return False



# Función para detectar el sistema operativo

def detect_os():

    """Detecta el sistema operativo en el que se ejecuta el script."""
    os_name = platform.system().lower()

    if os_name == "windows":
        return "windows"

    elif os_name == "darwin":
        return "macos"

    elif os_name == "linux":
        return "ubuntu"

    else:
        raise Exception("Sistema operativo no soportado.")



# Función para instalar Docker en Windows

def install_docker_windows():

    """Instala Docker en Windows."""
    print("Instalando Docker en Windows...")

    try:
        subprocess.run(["winget", "install", "Docker.DockerDesktop"], check=True)
        print("Docker instalado correctamente en Windows.")

    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en Windows.")
        sys.exit(1)



# Función para instalar Docker en macOS

def install_docker_macos():

    """Instala Docker en macOS."""
    print("Instalando Docker en macOS...")

    try:
        subprocess.run(["brew", "install", "docker"], check=True)
        print("Docker instalado correctamente en macOS.")

    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en macOS.")
        sys.exit(1)



# Función para instalar Docker en Ubuntu

def install_docker_ubuntu():

    """Instala Docker en Ubuntu."""
    print("Instalando Docker en Ubuntu...")

    try:
        subprocess.run(["sudo", "apt-get", "update"], check=True)
        subprocess.run(["sudo", "apt-get", "install", "-y", "docker.io"], check=True)
        subprocess.run(["sudo", "systemctl", "start", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "enable", "docker"], check=True)
        print("Docker instalado correctamente en Ubuntu.")

    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en Ubuntu.")
        sys.exit(1)



# Función para crear un archivo docker-compose.yml

def create_docker_compose_file():

    """Crea el archivo docker-compose.yml con la configuración básica para Spark."""
    print("Creando archivo docker-compose.yml...")

    docker_compose_content = """
    version: "3"
    services:
      master:
        image: bitnami/spark:latest
        container_name: spark-master
        environment:
          - SPARK_MODE=master
        ports:
          - "8080:8080"
          - "7077:7077"
      worker:
        image: bitnami/spark:latest
        container_name: spark-worker
        environment:
          - SPARK_MODE=worker
          - SPARK_MASTER=spark://spark-master:7077
        depends_on:
          - master
    """

    try:
        with open("docker-compose.yml", "w") as f:
            f.write(docker_compose_content)
        print("Archivo docker-compose.yml creado correctamente.")

    except Exception as e:
        print(f"Error al crear el archivo docker-compose.yml: {e}")
        sys.exit(1)



# Función principal

def main():

    """Función principal que coordina la instalación de Docker y la creación de docker-compose.yml."""
    # Detecta el sistema operativo
    os_name = detect_os()


    # Verifica si Docker está instalado
    if not is_docker_installed():

        if os_name == "windows":
            install_docker_windows()

        elif os_name == "macos":
            install_docker_macos()

        elif os_name == "ubuntu":
            install_docker_ubuntu()

        else:
            print("Sistema operativo no soportado para la instalación de Docker.")
            sys.exit(1)


    # Verifica si Docker Compose está instalado
    if shutil.which("docker-compose") is None:

        print("Docker Compose no está instalado. Instalando...")

        try:
            subprocess.run(["sudo", "apt-get", "install", "-y", "docker-compose"], check=True)
            print("Docker Compose instalado correctamente.")

        except subprocess.CalledProcessError:
            print("Error al intentar instalar Docker Compose.")
            sys.exit(1)

    # Crea el archivo docker-compose.yml
    create_docker_compose_file()

    # Inicia el clúster de Docker usando docker-compose
    # print("Iniciando el clúster de Spark...")

    # try:
        # subprocess.run(["docker-compose", "up", "-d"], check=True)
        # print("Clúster de Spark iniciado correctamente.")

    # except subprocess.CalledProcessError:
        # print("Error al intentar iniciar el clúster con Docker Compose.")
        # sys.exit(1)



# Ejecuta la función principal
if __name__ == "__main__":
    main()

"""# **Mejora de la segunda propuesta**

Aquí modificamos el script original para ampliar el soporte a distribuciones Linux. Ahora se detectan y se manejan (al menos) las siguientes distribuciones:

* Ubuntu (y derivados basados en Debian)
* Debian
* CentOS
* Fedora
* Arch Linux
"""

import subprocess
import sys
import os
import platform
import shutil

# Función para verificar si Docker está instalado
def is_docker_installed():
    """Verifica si Docker está instalado en el sistema."""
    try:
        subprocess.run(["docker", "--version"], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print("Docker está instalado.")
        return True
    except subprocess.CalledProcessError:
        print("Docker no está instalado.")
        return False

# Función para detectar la distribución de Linux leyendo /etc/os-release
def detect_linux_distro():
    distro_id = "unknown"
    try:
        with open("/etc/os-release") as f:
            for line in f:
                if line.startswith("ID="):
                    distro_id = line.strip().split("=")[1].strip('"').lower()
                    break
    except Exception as e:
        print(f"No se pudo detectar la distribución Linux: {e}")
    return distro_id

# Función para detectar el sistema operativo
def detect_os():
    """Detecta el sistema operativo en el que se ejecuta el script."""
    os_name = platform.system().lower()
    if os_name == "windows":
        return "windows"
    elif os_name == "darwin":
        return "macos"
    elif os_name == "linux":
        # Detecta la distribución específica de Linux
        distro = detect_linux_distro()
        if distro in ["ubuntu", "debian"]:
            return distro
        elif distro in ["centos", "fedora", "arch"]:
            return distro
        else:
            # Si no se reconoce la distro, se asume como "linux"
            return "linux"
    else:
        raise Exception("Sistema operativo no soportado.")

# Función para instalar Docker en Windows
def install_docker_windows():
    """Instala Docker en Windows."""
    print("Instalando Docker en Windows...")
    try:
        subprocess.run(["winget", "install", "Docker.DockerDesktop"], check=True)
        print("Docker instalado correctamente en Windows.")
    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en Windows.")
        sys.exit(1)

# Función para instalar Docker en macOS
def install_docker_macos():
    """Instala Docker en macOS."""
    print("Instalando Docker en macOS...")
    try:
        subprocess.run(["brew", "install", "docker"], check=True)
        print("Docker instalado correctamente en macOS.")
    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en macOS.")
        sys.exit(1)

# Función para instalar Docker en distribuciones basadas en Debian (Ubuntu, Debian)
def install_docker_debian():
    """Instala Docker en sistemas basados en Debian/Ubuntu."""
    print("Instalando Docker en sistema basado en Debian/Ubuntu...")
    try:
        subprocess.run(["sudo", "apt-get", "update"], check=True)
        subprocess.run(["sudo", "apt-get", "install", "-y", "docker.io"], check=True)
        subprocess.run(["sudo", "systemctl", "start", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "enable", "docker"], check=True)
        print("Docker instalado correctamente en Debian/Ubuntu.")
    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en Debian/Ubuntu.")
        sys.exit(1)

# Función para instalar Docker en CentOS
def install_docker_centos():
    """Instala Docker en CentOS."""
    print("Instalando Docker en CentOS...")
    try:
        subprocess.run(["sudo", "yum", "install", "-y", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "start", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "enable", "docker"], check=True)
        print("Docker instalado correctamente en CentOS.")
    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en CentOS.")
        sys.exit(1)

# Función para instalar Docker en Fedora
def install_docker_fedora():
    """Instala Docker en Fedora."""
    print("Instalando Docker en Fedora...")
    try:
        subprocess.run(["sudo", "dnf", "install", "-y", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "start", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "enable", "docker"], check=True)
        print("Docker instalado correctamente en Fedora.")
    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en Fedora.")
        sys.exit(1)

# Función para instalar Docker en Arch Linux
def install_docker_arch():
    """Instala Docker en Arch Linux."""
    print("Instalando Docker en Arch Linux...")
    try:
        subprocess.run(["sudo", "pacman", "-Syu", "--noconfirm", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "start", "docker"], check=True)
        subprocess.run(["sudo", "systemctl", "enable", "docker"], check=True)
        print("Docker instalado correctamente en Arch Linux.")
    except subprocess.CalledProcessError:
        print("Error al intentar instalar Docker en Arch Linux.")
        sys.exit(1)

# Función para instalar Docker en Linux, delegando según la distribución detectada
def install_docker_linux(distro):
    if distro in ["ubuntu", "debian"]:
        install_docker_debian()
    elif distro == "centos":
        install_docker_centos()
    elif distro == "fedora":
        install_docker_fedora()
    elif distro == "arch":
        install_docker_arch()
    else:
        print("Distribución Linux no soportada para la instalación automática de Docker.")
        sys.exit(1)

# Función para instalar Docker Compose según el sistema operativo
def install_docker_compose(os_type):
    if os_type in ["ubuntu", "debian", "centos", "fedora", "arch", "linux"]:
        print("Docker Compose no está instalado. Instalando...")
        # Se asume que en sistemas Linux se usa el gestor de paquetes correspondiente o se instala vía pip
        if os_type in ["ubuntu", "debian"]:
            try:
                subprocess.run(["sudo", "apt-get", "install", "-y", "docker-compose"], check=True)
                print("Docker Compose instalado correctamente.")
            except subprocess.CalledProcessError:
                print("Error al intentar instalar Docker Compose en Debian/Ubuntu.")
                sys.exit(1)
        elif os_type in ["centos", "fedora"]:
            try:
                subprocess.run(["sudo", "yum", "install", "-y", "docker-compose"], check=True)
                print("Docker Compose instalado correctamente.")
            except subprocess.CalledProcessError:
                print("Error al intentar instalar Docker Compose en CentOS/Fedora.")
                sys.exit(1)
        elif os_type == "arch":
            try:
                subprocess.run(["sudo", "pacman", "-Syu", "--noconfirm", "docker-compose"], check=True)
                print("Docker Compose instalado correctamente.")
            except subprocess.CalledProcessError:
                print("Error al intentar instalar Docker Compose en Arch Linux.")
                sys.exit(1)
        else:
            # Como alternativa, se puede instalar vía pip
            try:
                subprocess.run(["sudo", "pip", "install", "docker-compose"], check=True)
                print("Docker Compose instalado correctamente vía pip.")
            except subprocess.CalledProcessError:
                print("Error al intentar instalar Docker Compose vía pip.")
                sys.exit(1)
    else:
        print("Instalación de Docker Compose no soportada para este sistema operativo.")
        sys.exit(1)

# Función para crear un archivo docker-compose.yml
def create_docker_compose_file():
    """Crea el archivo docker-compose.yml con la configuración básica para Spark."""
    print("Creando archivo docker-compose.yml...")
    docker_compose_content = """
version: "3"
services:
  master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
  worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - master
"""
    try:
        with open("docker-compose.yml", "w") as f:
            f.write(docker_compose_content)
        print("Archivo docker-compose.yml creado correctamente.")
    except Exception as e:
        print(f"Error al crear el archivo docker-compose.yml: {e}")
        sys.exit(1)

# Función principal
def main():
    """Función principal que coordina la instalación de Docker y la creación de docker-compose.yml."""
    os_type = detect_os()
    print(f"Sistema detectado: {os_type}")

    # Verifica si Docker está instalado
    if not is_docker_installed():
        if os_type == "windows":
            install_docker_windows()
        elif os_type == "macos":
            install_docker_macos()
        elif os_type in ["ubuntu", "debian", "centos", "fedora", "arch", "linux"]:
            install_docker_linux(os_type)
        else:
            print("Sistema operativo no soportado para la instalación de Docker.")
            sys.exit(1)

    # Verifica si Docker Compose está instalado
    if shutil.which("docker-compose") is None:
        install_docker_compose(os_type)

    # Crea el archivo docker-compose.yml
    create_docker_compose_file()

    # Inicia el clúster de Docker usando docker-compose (opcional descomentando)
    # print("Iniciando el clúster de Spark...")
    # try:
    #     subprocess.run(["docker-compose", "up", "-d"], check=True)
    #     print("Clúster de Spark iniciado correctamente.")
    # except subprocess.CalledProcessError:
    #     print("Error al intentar iniciar el clúster con Docker Compose.")
    #     sys.exit(1)

if __name__ == "__main__":
    main()